site_name: "My Notes"
nav:
  - Home: README.md
  - Notes:
    - k8s:
      - "note 1": "K8s-cluster Initial Setup using bash.md"
      - "note 2": "Boot-strapping k8s cluster.md"


theme:
  name: "material"
  palette:
    - dark
    - light
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.sections.tabs
    - navigation.sections.tabs.sticky